# Generated by Django 5.1.3 on 2024-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE(Regular)', 'CSE(R)'), ('CSE(Honors)', 'CSE(H)'), ('CS&IT', 'CSIT')], max_length=100),
        ),
    ]
