# Generated by Django 5.1.3 on 2024-11-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_faculty_department_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='year',
        ),
    ]
