# Generated by Django 5.1.3 on 2024-12-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_course_program_alter_course_academicyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='ltps',
            field=models.CharField(default='0-0-0-0', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FacultyCourseMapping',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practical'), ('S', 'Skill')], max_length=10)),
                ('type', models.BooleanField()),
                ('section', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
            ],
            options={
                'db_table': 'facultycoursemapping_table',
            },
        ),
    ]
