# Generated by Django 5.1.3 on 2024-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_course_course_credits_course_ltps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultycoursemapping',
            name='section',
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='sectionalloted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
