# Generated by Django 5.1.3 on 2024-12-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_facultycoursemapping_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultycoursemapping',
            name='component',
        ),
        migrations.RemoveField(
            model_name='facultycoursemapping',
            name='type',
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='components',
            field=models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practical'), ('S', 'Skill')], default='L', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='facultytype',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
