# Generated by Django 5.1.3 on 2024-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_remove_facultycoursemapping_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycoursemapping',
            name='facultytype',
            field=models.BooleanField(verbose_name='Faculty Type(Main/Assistence'),
        ),
    ]
