# Generated by Django 5.1.3 on 2024-12-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_facultycoursemapping_facultytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycoursemapping',
            name='facultytype',
            field=models.BooleanField(verbose_name='Faculty Type'),
        ),
    ]
