# Generated by Django 5.1.3 on 2024-12-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_facultycoursemapping_facultytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_credits',
            new_name='coursecredits',
        ),
    ]
