# Generated by Django 5.1.3 on 2024-12-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_rename_course_credits_course_coursecredits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ltps',
            new_name='LTPS',
        ),
    ]
