# Generated by Django 5.1.3 on 2024-12-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_rename_ltps_course_ltps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='LTPS',
            new_name='LTPSK',
        ),
    ]
