# Generated by Django 4.1.1 on 2024-12-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_rename_ltps_course_ltpsk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='LTPSK',
            new_name='ltps',
        ),
    ]
