# Generated by Django 4.1.1 on 2024-12-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_rename_ltpsk_course_ltps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ltps',
            new_name='ltpsk',
        ),
    ]
