# Generated by Django 4.1.1 on 2024-12-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_rename_ltps_course_ltpsk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ltpsk',
            new_name='LTPSK',
        ),
    ]
